/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.util.Vector;
import controller.Colas;
import model.Vendedor;
import java.awt.Component;
import javax.swing.JOptionPane;
/**
 *
 * @author Nelson
 */
public class MenuVendedor extends javax.swing.JPanel {

    /**
     * Creates new form MenuVendedor2
     */
    Vector<Object>Listasexo;
    Vector<Object>listaNodo;
    
    public MenuVendedor() {
        initComponents();
        Listasexo=new Vector<Object>();
        listaNodo=new Vector<Object>();
        seleccion();
        listasElementos();
    }
    
    Colas a=new Colas();

    public void seleccion(){
        Listasexo.add("Masculino");
        Listasexo.add("Femenino");
        for(int i=0;i<Listasexo.size();i++){
            itemsexo.addItem(Listasexo.get(i));
        }
    }
   
    public void agregarElementos(){
        Vendedor c=new Vendedor(txtcedula.getText(),txtapellido.getText(),txtnombre.getText(),itemsexo.getSelectedItem().toString(),txtedad.getText());
        a.encolar(c);
        limpiar();
    }
    public void listasElementos(){
        
        jTextArea1.setText(a.presentar());   

    }
    
    
    public void eliminar(){
        if(a.size() > 0){
        a.desencolar();
        }
    }
    public void Operacion(){
        if(itemOperaciones.getSelectedItem().equals("Desencolar")){
            eliminar();
        }if(itemOperaciones.getSelectedItem().equals("Encolar")){
            agregarElementos();
        }
    }
    
    public void limpiar(){
        txtnombre.setText(null);
        txtcedula.setText(null);
        txtapellido.setText(null);
        txtedad.setText(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        itemOperaciones = new javax.swing.JComboBox();
        btnEliminarlista = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtedad = new javax.swing.JTextField();
        itemsexo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Vendedor");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 50));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 90, -1));

        btnAgregar.setText("Encolar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, -1));

        itemOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Encolar", "Desencolar" }));
        itemOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(itemOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        btnEliminarlista.setText("Desencolar");
        btnEliminarlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarlistaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        btnCalcular.setText("Aceptar");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 90, -1));

        jLabel6.setText("Edad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, 760, 360));
        jPanel1.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 50, -1));

        itemsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsexoActionPerformed(evt);
            }
        });
        jPanel1.add(itemsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 90, -1));

        jLabel4.setText("Nombres");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 20));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, -1));

        jLabel5.setText("Sexo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, 20));
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, -1));

        jLabel2.setText("DNI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 20));

        jLabel3.setText("Apellidos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 120, -1));

        jLabel9.setText("Operaciones");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuBackground.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        listasElementos();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarElementos();
        listasElementos();
        JOptionPane.showMessageDialog(this, "Se agrego correctamente");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void itemOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOperacionesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_itemOperacionesActionPerformed

    private void btnEliminarlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarlistaActionPerformed
        // TODO add your handling code here:
        eliminar();
        listasElementos();
    }//GEN-LAST:event_btnEliminarlistaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        Operacion();

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void itemsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsexoActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_itemsexoActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnEliminarlista;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel fondo;
    private javax.swing.JComboBox itemOperaciones;
    private javax.swing.JComboBox itemsexo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
