package vista;

import controller.Negocio;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.Producto;
import model.Venta;

/*@author Nelson*/
public class MenuVenta extends javax.swing.JPanel {
    /*=========================================*/
    /*<<--- PilasVenta Nelson (AVANCE 2) ---->>*/
    /*=========================================*/
    
    Negocio obj;
    public MenuVenta(Negocio principal) {
        initComponents();
        this.obj = principal;
        actualizarTabla();
    }
    
    int item = 0;
    double totalpagar = 0;
    int pres = 0;
    
    private void totalPagarVenta(){
        totalpagar = 0;
        int numFila = tablaHelp.getRowCount();
        for(int i = 0; i < numFila; i++){
            double cal = Double.parseDouble(String.valueOf(tablaHelp.getModel().getValueAt(i, 4)));
            totalpagar = totalpagar + cal;
        }
        txtPaga.setText(String.format("%.2f", totalpagar));
    }
    
    private void limpiarVenta(){
        txtID.setText("");
        txtDescripcionPro.setText("");
        txtCant.setText("");
        txtStockDis.setText("");
        txtPre.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtDescripcionPro = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        txtStockDis = new javax.swing.JTextField();
        txtPre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHelp = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPaga = new javax.swing.JTextField();
        btnVender = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnDetalles = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtVend = new javax.swing.JLabel();
        btnBuscarProdc = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        btnEliminarPila = new javax.swing.JButton();
        btnDesapilar = new javax.swing.JButton();
        btnIrDetalle = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        jLabel5.setText("STOCK DIS.");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CODIGO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));

        jLabel2.setText("PRODUCTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 20));

        jLabel3.setText("CANTIDAD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        jLabel4.setText("PRECIO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 20));

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(218, 229, 235));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, -1));

        txtDescripcionPro.setEditable(false);
        txtDescripcionPro.setBackground(new java.awt.Color(218, 229, 235));
        jPanel1.add(txtDescripcionPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 230, -1));

        txtCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantActionPerformed(evt);
            }
        });
        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantKeyPressed(evt);
            }
        });
        jPanel1.add(txtCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 130, -1));

        txtStockDis.setEditable(false);
        txtStockDis.setBackground(new java.awt.Color(218, 229, 235));
        jPanel1.add(txtStockDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 120, -1));

        txtPre.setEditable(false);
        txtPre.setBackground(new java.awt.Color(218, 229, 235));
        jPanel1.add(txtPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 120, -1));

        jLabel6.setText("STOCK DIS.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 70, 20));

        tablaHelp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaHelp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 760, 240));

        jLabel7.setText("DNI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 20));

        jLabel8.setText("NOMBRE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, 20));

        jLabel9.setText("TOTAL A PAGAR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, 20));

        txtDNI.setEditable(false);
        txtDNI.setBackground(new java.awt.Color(218, 229, 235));
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 90, -1));

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(218, 229, 235));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 230, -1));

        txtPaga.setEditable(false);
        txtPaga.setBackground(new java.awt.Color(226, 241, 232));
        txtPaga.setText("En Proceso");
        jPanel1.add(txtPaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 160, -1));

        btnVender.setText("VENDER");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 90, -1));

        btnVentas.setText("Mostrar Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 120, -1));

        btnDetalles.setText("Mostrar Detalles");
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });
        jPanel1.add(btnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 130, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel10.setText("Venta");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        txtVend.setText("VENDEDOR1");
        jPanel1.add(txtVend, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        btnBuscarProdc.setText("BuscarPro");
        btnBuscarProdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdcActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarProdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 140, 120, -1));

        btnBuscarCliente.setText("BuscarCli");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 20, 100));

        jLabel11.setText("Info Venta en Pila");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 100, -1));

        btnEliminarPila.setText("Eliminar Venta (Pila)");
        btnEliminarPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPilaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarPila, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 140, -1));

        btnDesapilar.setText("Desapilar");
        btnDesapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesapilarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesapilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 140, -1));

        btnIrDetalle.setText("Ir a Detalles");
        btnIrDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrDetalleActionPerformed(evt);
            }
        });
        jPanel1.add(btnIrDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 150, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MenuBackground.png"))); // NOI18N
        fondo.setText("jLabel2");
        fondo.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                int cod = Integer.parseInt(txtID.getText());
                Producto pro = obj.BuscarPro(cod);
                if(pro.getInfo() != null){
                    txtDescripcionPro.setText("" + pro.getInfo());
                    txtPre.setText(""+pro.getPrecio());
                    txtStockDis.setText(""+ pro.getCantidad());
                    txtCant.requestFocus();
                } else {
                    txtDescripcionPro.setText("");
                    txtPre.setText("");
                    txtStockDis.setText("");
                    txtID.requestFocus();
                }
            
        }
        
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtCantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyPressed
        
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!"".equals(txtCant.getText())){
                //Pila de IdProducto
                obj.PilaVenta(Integer.parseInt(txtID.getText()),Integer.parseInt(txtCant.getText()));
                
                int cod = Integer.parseInt(txtID.getText());
                String desc = txtDescripcionPro.getText();
                int cant = Integer.parseInt(txtCant.getText());
                double precio = Double.parseDouble(txtPre.getText());
                double total = cant * precio;
                int stock = Integer.parseInt(txtStockDis.getText());
                
                if(stock >= cant){
                    item = item +1;
                    pres = pres + 1;
                    actualizarTabla();
                    
                    LimpiarVenta();
                } else {
                    JOptionPane.showMessageDialog(null, "Stock no disponible");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese cantidad");
            }
        }
    
    }//GEN-LAST:event_txtCantKeyPressed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        boolean fieldDNI=true, fieldPago=true;
        if(txtDNI.getText().equals("")){fieldDNI=false;}
        if(txtPaga.getText().equals("") || Double.parseDouble(txtPaga.getText())==0){fieldPago=false;}
        
        System.out.println("txttDni: "+fieldDNI+" - txtPago: "+fieldPago);
        if (fieldDNI && fieldPago) {
            RegistrarDetalle();
            RegistrarVenta();
            actualizarStock();

            obj.eliminarTodoPila();
            
            DefaultTableModel model = (DefaultTableModel) tablaHelp.getModel();
            model.setRowCount(0);

            txtDNI.setText("");
            txtName.setText("");
            txtVend.setText("");
            txtPaga.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Falta rellenar datos en la venta!",
      "Faltan Datos!!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVenderActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnBuscarProdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdcActionPerformed
        // TODO add your handling code here:
        frmBuscarProd f1 = new frmBuscarProd(obj);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        
    }//GEN-LAST:event_btnBuscarProdcActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        frmBuscarCliente f1 = new frmBuscarCliente(obj);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        obj.soutVentas();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        obj.soutDetalles();
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void txtCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantActionPerformed

    private void btnDesapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesapilarActionPerformed
        int respuesta = JOptionPane.showOptionDialog(
            null,
            "Esto DESAPILARA elmento en la venta",
            "Advertencia",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            new Object[]{"Sí", "No"},
            "No"
        );
        
        if (respuesta == JOptionPane.YES_OPTION) {
            
            obj.eliminarPila();
            actualizarTabla();
            if(obj.vacioPila()){txtPaga.setText("");}
        }
    }//GEN-LAST:event_btnDesapilarActionPerformed

    private void btnEliminarPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPilaActionPerformed
        int respuesta = JOptionPane.showOptionDialog(
            null,
            "Esto ELIMINARA toda la Venta(PILA)",
            "Advertencia",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            new Object[]{"Sí", "No"},
            "No"
        );
        
        if (respuesta == JOptionPane.YES_OPTION) {
            obj.eliminarTodoPila();
            actualizarTabla();
            txtPaga.setText("");
        }
    }//GEN-LAST:event_btnEliminarPilaActionPerformed

    private void btnIrDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrDetalleActionPerformed
        MenuDetalles mdet = new MenuDetalles(obj);      
        mdet.setSize(800,600);
        mdet.setLocation(0,0);
        
        this.removeAll();
        this.add(mdet, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btnIrDetalleActionPerformed

    public void actualizarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tablaHelp.getModel(); 
        modelo.setRowCount(0);
        modelo = obj.tablaPila(modelo);
        tablaHelp.setModel(modelo);
        TotalPagar();
    }
    
    public void RegistrarVenta(){
        String cliente = txtName.getText();
        String vendedor = txtVend.getText();
        double monto = totalpagar;
        obj.RegistrarVenta(cliente, vendedor, monto);
    }
    
    public void RegistrarDetalle(){
        int idventa=Venta.getContar();
        for(int i = 0; i < tablaHelp.getRowCount(); i++){
            int cod = Integer.parseInt(tablaHelp.getValueAt(i, 0).toString());
            int cant = Integer.parseInt(tablaHelp.getValueAt(i, 2).toString());
            double precio = Double.parseDouble(tablaHelp.getValueAt(i, 3).toString());
            
            obj.RegistrarDetalle(cod, cant,precio, idventa);
        }
    }
    
    private void actualizarStock(){
        for(int i = 0; i < tablaHelp.getRowCount(); i++){
            String cod = tablaHelp.getValueAt(i, 0).toString();
            int cant = Integer.parseInt(tablaHelp.getValueAt(i, 2).toString());
            Producto p1 = new Producto();
            p1 = obj.BuscarPro(Integer.parseInt(cod));
            int stockAct = p1.getCantidad() - cant;
            obj.actualizarStock(stockAct, cod);
        }
    }
    
    public void TotalPagar(){
        totalpagar = 0;
        int numFila = tablaHelp.getRowCount();
        for(int i = 0; i < numFila; i++){
            double cal = Double.parseDouble(String.valueOf(tablaHelp.getModel().getValueAt(i, 4)));
            totalpagar = totalpagar + cal;
        }
        txtPaga.setText(String.format("%.2f", totalpagar));
    }
    
    public void LimpiarVenta(){
        txtID.setText("");
        txtDescripcionPro.setText("");
        txtCant.setText("");
        txtPre.setText("");
        txtStockDis.setText("");
        txtCant.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProdc;
    private javax.swing.JButton btnDesapilar;
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnEliminarPila;
    private javax.swing.JButton btnIrDetalle;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaHelp;
    private javax.swing.JTextField txtCant;
    public static javax.swing.JTextField txtDNI;
    public static javax.swing.JTextField txtDescripcionPro;
    public static javax.swing.JTextField txtID;
    public static javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPaga;
    public static javax.swing.JTextField txtPre;
    public static javax.swing.JTextField txtStockDis;
    private javax.swing.JLabel txtVend;
    // End of variables declaration//GEN-END:variables
}

    
